mysql:
  type: mysql
  user: root
  password: 123456
  host: 127.0.0.1:3306
  name: douyin_db
  max-idle-cons: 10
  max-open-cons: 100
jwt:
  signing-key: ZcyPlus
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
minio:
  end-point: 127.0.0.1:9000
  access-key-id: minioadmin
  secret-access-key: minioadmin
system:
  RouterPrefix: ""
  port: :8080